branches:
  - Branch: main
    type: GITHUB_REL
attributes:
  prepareDeployPackage: true
  finalAssembly_restrictedPromotion: false
  finalAssembly_customerRelease: true
  finalAssembly_internalRelease: false
  releasestaging: true
  milestonestaging: true
  cloudshipment: true
